// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Button(Props) {
  return React.createElement("button", {
              onClick: (function (param) {
                  console.log("clicked button");
                  
                })
            }, "hi");
}

var make = Button;

export {
  make ,
  
}
/* react Not a pure module */
